import { Good, BorderCrossing, PortGoodsMatrix, RegulationRef } from "./types";

export const GOODS: Good[] = [
  { id: 'plant', icon: '🌱', name: 'Ургамлын үр, үрслэг, суулгац', sources: { import: 'ЗГ №173', export: 'ЗГ №190' }, detail: 'Ургамлын үр, үрслэг, суулгац нэвтрүүлэх.' },
  { id: 'animal', icon: '🐄', name: 'Мал, амьтан, үржлийн мал', sources: { import: 'ЗГ №173', export: 'ЗГ №190' }, detail: 'Мал, амьтан болон үржлийн мал нэвтрүүлэх.' },
  { id: 'embryo', icon: '🧬', name: 'Мал амьтны үр, хөврөл үр', sources: { import: 'ЗГ №173', export: 'ЗГ №173' }, detail: 'Мал амьтны үр, хөврөл үр, бичил биетний өсгөвөр, эмгэгт материал.' },
  { id: 'meat', icon: '🥩', name: 'Түүхий мах, дайвар бүтээгдэхүүн', sources: { import: 'ЗГ №173', export: 'ЗГ №173' }, detail: 'Түүхий мах болон дайвар бүтээгдэхүүн.' },
  { id: 'medicine', icon: '💊', name: 'Эм, эмнэлгийн хэрэгсэл', sources: { import: 'ЗГ №73', export: 'ЗГ №73' }, detail: 'Эм, эмнэлгийн хэрэгсэл.' },
  { id: 'chemical', icon: '☣️', name: 'Химийн хорт болон аюултай бодис', sources: { import: 'ЗГ №296', export: 'ЗГ №296' }, detail: 'Химийн хорт ба аюултай бодис.' },
  { id: 'explosive', icon: '💥', name: 'Тэсэрч дэлбэрэх бодис', sources: { import: 'ЗГ №149', export: 'ЗГ №149' }, detail: 'Тэсэрч дэлбэрэх бодис ба тэсэлгээний хэрэгсэл.' },
  { id: 'alcohol', icon: '🍺', name: 'Согтууруулах ундаа', sources: { import: 'ЗГ №146/2023', export: 'ЗГ №146/2023' }, detail: 'Бүх төрлийн согтууруулах ундаа.' },
  { id: 'pesticide', icon: '🌾', name: 'Ургамал хамгааллын бодис, бордоо', sources: { import: 'ЗГ №146/2011', export: 'ЗГ №146/2011' }, detail: 'Ургамал хамгааллын бодис, бордоо.' },
  { id: 'gmo', icon: '🧪', name: 'Хувиргасан амьд организм', sources: { import: 'ЗГ №158', export: 'ЗГ №158' }, detail: 'Хувиргасан амьд организм (ГМО).' },
  { id: 'oil', icon: '⛽', name: 'Газрын тосны бүтээгдэхүүн', sources: { import: 'Онцгой албан татвар', export: 'Онцгой албан татвар' }, detail: 'Автобензин, дизелийн түлш.' },
];

export const borderCrossings: BorderCrossing[] = [
  { 
    id: 'zamiin-uud', 
    name: 'Замын-Үүд', 
    region: 'Дорноговь', 
    direction: 'Зүүн (Хятад)', 
    lat: 43.7083, 
    lng: 111.9028, 
    ubDistance: 650, 
    aimagDistance: 210, 
    aimagLat: 44.8876,
    aimagLng: 110.1345, // Sainshand (Dornogovi)
    neighborPortName: "Эрээн (БНХАУ)",
    operationalStatus: "Олон улсын", 
    trafficStatus: "Ачаалалтай",
    transportTypes: ["Автозам", "Төмөр зам"],
    capacity: 1500,
    development: {
      projectName: '"Хөгжлийн хөтөч" дэд бүтцийн төсөл',
      progress: 100,
      budget: 'МУ: 25.5 тэрбум ₮, БНХАУ: 106.9 тэрбум ₮',
      contractor: 'Жун Мэй Инженеринг Групп ХХК',
      description: 'Хилийн боомтын дэд бүтэц, барилга байгууламжийн шинэчлэл бүрэн дууссан. Зорчигч болон ачаа тээврийн цогцолбор ашиглалтад орсон.',
      imageUrl: 'https://i0.wp.com/cdn.mminfo.mn/sh/mminfo/2024/01/21/11/04/30/1e0ffae78d594b29f0464670b8a24ca3.jpg'
    },
    areaSize: 25000,
    staffGUAB: 45,
    staffGUB: 120,
    warehousesCount: 8,
    controlZonesCount: 4,
    imageUrl: "https://i0.wp.com/upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Zamiin_Uud_border_crossing.jpg/640px-Zamiin_Uud_border_crossing.jpg",
    description: "Монгол Улсын хамгийн том, стратегийн чухал ач холбогдолтой хилийн боомт. Ачаа болон зорчигч тээврийн гол зангилаа.",
    hasLaboratory: true,
    labCapacity: "Гаалийн төв лабораторын салбар лаборатори",
    labCapabilities: [
      "Хүнсний эрүүл ахуй, хорио цээр",
      "Химийн хорт болон аюултай бодис",
      "Эрдэс баялаг, нүүрс",
      "Мансууруулах болон сэтгэцэд нөлөөт бодис",
      "Ноос, ноолуур, малын гаралтай ширхэгт материал"
    ],
    infrastructure: {
      totalArea: "18.6 га",
      details: ["Шалган нэвтрүүлэх цогцолбор шинэчлэгдсэн", "Ухаалаг гарц системтэй", "Хүчин чадал 5 дахин нэмэгдсэн"]
    },
    legalImports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173'] },
      { goodId: 'animal', text: 'Мал, амьтан, үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', resolutions: ['ЗГ №73'] },
      { goodId: 'chemical', text: 'Химийн хорт бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №149'] },
      { goodId: 'alcohol', text: 'Бүх төрлийн согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 750к, ДТ: 850к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'embryo', text: 'Мал амьтны үр, хөврөл үр, эмгэгт материал', resolutions: ['ЗГ №173'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №149'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
  },
  { 
    id: 'altanbulag', 
    name: 'Алтанбулаг', 
    region: 'Сэлэнгэ', 
    direction: 'Хойд (Орос)', 
    lat: 50.3167, 
    lng: 106.5167, 
    ubDistance: 350, 
    aimagDistance: 23, 
    aimagLat: 50.2333,
    aimagLng: 106.2000, // Sukhbaatar (Selenge)
    neighborPortName: "Хиагт (ОХУ)",
    operationalStatus: "Олон улсын", 
    trafficStatus: "Хэвийн",
    transportTypes: ["Автозам"],
    capacity: 800,
    development: {
      projectName: 'RIBS бүс нутгийн төсөл (АХБ)',
      progress: 100,
      budget: '$12.1 сая ам.доллар',
      contractor: '"Эйч Кэ Би Интернэйшнл Холдинг" ХХК',
      description: 'Алтанбулаг боомтын барилга байгууламжийг сайжруулах, өргөтгөх, шинэчлэх ажил 100% дууссан.',
      imageUrl: 'https://i0.wp.com/montsame.mn/files/612de34d284a8.jpeg'
    },
    hasLaboratory: true,
    labCapacity: "Гаалийн төв лабораторын салбар лаборатори",
    labCapabilities: ["Хүнсний эрүүл ахуй, хорио цээр", "Химийн хорт болон аюултай бодис", "Мансууруулах болон сэтгэцэд нөлөөт бодис", "Архи, согтууруулах ундаа"],
    infrastructure: {
      totalArea: "7.13 га",
      passengerZone: "3.37 га",
      cargoZone: "3.43 га",
      details: ["Дэд бүтцийн хэсэг: 0.33 га", "Олон улсын жишигт нийцсэн шинэ цогцолбор", "Зорчигч тээвэрлэх хүчин чадал: 2.22 га талбайтай"]
    },
    legalImports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173'] },
      { goodId: 'animal', text: 'Мал, амьтан, үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', resolutions: ['ЗГ №73'] },
      { goodId: 'chemical', text: 'Химийн хорт бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №149'] },
      { goodId: 'alcohol', text: 'Бүх төрлийн согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 750к, ДТ: 850к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'embryo', text: 'Мал амьтны үр, хөврөл үр, эмгэгт материал', resolutions: ['ЗГ №173'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №149'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
  },
  { 
    id: 'bichigt', 
    name: 'Бичигт', 
    region: 'Сүхбаатар', 
    direction: 'Зүүн (Хятад)', 
    lat: 45.8, 
    lng: 116.1, 
    ubDistance: 850, 
    aimagDistance: 295, 
    aimagLat: 46.6806,
    aimagLng: 113.2847, // Baruun-Urt (Sukhbaatar)
    neighborPortName: "Зүүн хатавч (БНХАУ)",
    operationalStatus: "Олон улсын", 
    trafficStatus: "Хэвийн",
    transportTypes: ["Автозам"],
    capacity: 500,
    development: {
      projectName: 'RIBS бүс нутгийн төсөл (АХБ)',
      progress: 35,
      budget: '$8.4 сая ам.доллар',
      description: 'Боомтын барилга байгууламж, дэд бүтцийн ажил үргэлжилж байна.',
      imageUrl: 'https://i0.wp.com/montsame.mn/files/64757c2c01ca7.jpeg'
    },
    infrastructure: {
      totalArea: "14 га",
      passengerZone: "4.97 га",
      cargoZone: "5.12 га",
      details: ["Хил хамгаалалтын бүс: 1.5 га", "Инженер хангамжийн бүс: 0.95 га", "Ачаа тээврийн цогцолбор: 5.12 га"]
    },
    legalImports: [
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'], conditions: 'зөвхөн үржлийн адуу' },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'chemical', text: 'Химийн хорт бодис', resolutions: ['ЗГ №296', '№66 нэмэлт'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №149', '№66 нэмэлт'] },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'plant', text: 'Ургамал, мал, амьтан экспорт', resolutions: ['ЗГ №190'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №149'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    proposedAdditions: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', targetResolution: 'ЗГ №173-д нэмэх', proposalNote: 'Лаборатори байгуулах шаардлагатай. Хорио цээрийн лаборатори болон Шинжээч ГУБ байхгүй. АХБ-ны төслийн хүрээнд 2026 оноос шинэчлэл хийгдэж 2028 онд ашиглалтанд орно.' },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа импорт', targetResolution: 'ЗГ №146/2023-д нэмэх' },
    ],
  },
  { 
    id: 'borshoo', 
    name: 'Боршоо', 
    region: 'Увс', 
    direction: 'Хойд (Орос)', 
    lat: 50.3, 
    lng: 92.4, 
    ubDistance: 1600, 
    aimagDistance: 124, 
    aimagLat: 49.9800,
    aimagLng: 92.0667, // Ulaangom (Uvs)
    neighborPortName: "Хандагайты (ОХУ)",
    operationalStatus: "Олон улсын", 
    trafficStatus: "Хэвийн",
    transportTypes: ["Автозам"],
    capacity: 500,
    development: {
      projectName: 'RIBS бүс нутгийн төсөл (АХБ)',
      progress: 100,
      budget: '$7.6 сая ам.доллар',
      description: 'Боршоо хилийн боомтын барилга байгууламж, тоног төхөөрөмжийг сайжруулах, өргөтгөх ажил дууссан.',
      imageUrl: 'https://i0.wp.com/montsame.mn/files/653243fcc889f.jpeg'
    },
    hasLaboratory: true,
    labCapabilities: ['Хүнс, ургамал, хорио цээр'],
    infrastructure: {
      totalArea: "10 га",
      passengerZone: "3232.0 м2 (Танхим)",
      details: ["Ерөнхий төлөвлөгөөний дагуу шинэчлэгдсэн", "Ачаа тээвэрлэх тусгай бүстэй"]
    },
    legalImports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173'] },
      { goodId: 'animal', text: 'Мал, амьтан, үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'pesticide', text: 'Ургамал хамгааллын бодис, бордоо', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    proposedAdditions: [
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', targetResolution: 'ЗГ №73-д нэмэх', proposalNote: 'Хорио цээрийн ГУБ анхан шатны хяналт хийх боломжтой.' },
      { goodId: 'meat', text: 'Түүхий мах импорт', targetResolution: 'ЗГ №173-д нэмэх' },
    ],
  },
  { id: 'sukhbaatar', name: 'Сүхбаатар', region: 'Сэлэнгэ', direction: 'Хойд (Орос)', lat: 50.2333, lng: 106.2167, ubDistance: 310, aimagDistance: 0, neighborPortName: "Наушки (ОХУ)", operationalStatus: "Олон улсын", trafficStatus: "Хэвийн", transportTypes: ["Төмөр зам"], capacity: 1200, 
    development: {
      projectName: 'Боомтын барилга, байгууламжийн шинэчлэл',
      progress: 95,
      budget: 'Төсвийн хөрөнгө оруулалт',
      description: 'Сүхбаатар төмөр замын боомтын захиргааны барилга болон шалган нэвтрүүлэх цогцолборын шинэчлэл.',
      imageUrl: 'https://i0.wp.com/montsame.mn/files/6397223b827e8.jpeg'
    },
    legalImports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173'] },
      { goodId: 'animal', text: 'Мал, амьтан, үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', resolutions: ['ЗГ №73'] },
      { goodId: 'chemical', text: 'Химийн хорт бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №149'] },
      { goodId: 'alcohol', text: 'Бүх төрлийн согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 750к, ДТ: 850к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'embryo', text: 'Мал амьтны үр, хөврөл үр, эмгэгт материал', resolutions: ['ЗГ №173'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №149'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
  },
  { id: 'bulgan-hovd', name: 'Булган (Ховд)', region: 'Ховд', direction: 'Баруун (Хятад)', lat: 46.1, lng: 91.1, ubDistance: 1556, aimagDistance: 400, aimagLat: 48.0, aimagLng: 91.64, neighborPortName: "Такашикэн (БНХАУ)", operationalStatus: "Олон улсын", trafficStatus: "Ачаалалтай", transportTypes: ["Автозам"], capacity: 700, 
    hasLaboratory: true,
    labCapabilities: ['Хүнс, ургамал, хорио цээр'],
    legalImports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173'] },
      { goodId: 'animal', text: 'Мал, амьтан, үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'pesticide', text: 'Ургамал хамгааллын бодис, бордоо', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
    ],
    legalExports: [
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    proposedAdditions: [
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', targetResolution: 'ЗГ №73-д нэмэх', proposalNote: 'АХБ-ны төслөөр 2027 оноос бүтээн байгуулалт эхэлж, химийн бодис болон бусад хорио цээрийн лаборатори, агуулах байгуулагдана.' },
      { goodId: 'chemical', text: 'Химийн хорт бодис', targetResolution: 'ЗГ №296-д нэмэх' },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', targetResolution: 'ЗГ №149-д нэмэх' },
      { goodId: 'meat', text: 'Түүхий мах импорт', targetResolution: 'ЗГ №173-д нэмэх' },
    ],
  },
  { id: 'gashuunsuhayt', name: 'Гашуунсухайт', region: 'Өмнөговь', direction: 'Урд (Хятад)', lat: 42.5833, lng: 107.5833, ubDistance: 800, aimagDistance: 342, aimagLat: 43.57, aimagLng: 104.42, neighborPortName: "Ганцмод (БНХАУ)", operationalStatus: "Олон улсын", trafficStatus: "Ачаалалтай", transportTypes: ["Автозам", "AGV"], capacity: 2500, 
    development: {
      projectName: '"Хөгжлийн хөтөч" дэд бүтцийн төсөл',
      progress: 100,
      budget: 'МУ: 32.6 тэрбум ₮, БНХАУ: 43.5 тэрбум ₮',
      contractor: 'Жун Мэй Инженеринг Групп ХХК',
      description: 'Хилийн боомтын дэд бүтэц, барилга байгууламжийн шинэчлэл бүрэн дууссан.',
      imageUrl: 'https://i0.wp.com/montsame.mn/files/64757c3fc1ecb.jpeg'
    },
    hasLaboratory: true,
    labCapacity: "Гаалийн төв лабораторын салбар лаборатори",
    labCapabilities: ["Эрдэс баялаг, нүүрс", "Химийн хорт болон аюултай бодис", "Мансууруулах болон сэтгэцэд нөлөөт бодис", "Хүнсний эрүүл ахуй, хорио цээр"],
    legalImports: [
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', resolutions: ['ЗГ №73', '№239 нэмэлт'] },
      { goodId: 'chemical', text: 'Химийн хорт бодис', resolutions: ['ЗГ №296', '№203 нэмэлт'], conditions: 'нөхцөл бүрдээгүй' },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №149', '№80 нэмэлт'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    proposedAdditions: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', targetResolution: 'ЗГ №173-д нэмэх', proposalNote: 'Хорио цээрийн лаборатори байгаа боловч ургамлын үр, үрслэг шинжилдэггүй, шинжээч-ГУБ байхгүй.' },
      { goodId: 'animal', text: 'Мал, амьтан импорт', targetResolution: 'ЗГ №173-д нэмэх' },
      { goodId: 'embryo', text: 'Мал амьтны үр, хөвөрл үр', targetResolution: 'ЗГ №173-д нэмэх' },
      { goodId: 'meat', text: 'Түүхий мах импорт', targetResolution: 'ЗГ №173-д нэмэх' },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа импорт', targetResolution: 'ЗГ №146/2023-д нэмэх' },
    ],
  },
  { id: 'shiveehuren', name: 'Шивээхүрэн', region: 'Өмнөговь', direction: 'Урд (Хятад)', lat: 42.7, lng: 101.4, ubDistance: 955, aimagDistance: 350, aimagLat: 43.57, aimagLng: 104.42, neighborPortName: "Сэхээ (БНХАУ)", operationalStatus: "Олон улсын", trafficStatus: "Квот тулсан", transportTypes: ["Автозам", "AGV"], capacity: 1100, 
    hasLaboratory: true,
    labCapabilities: ['Нүүрс'],
    legalImports: [
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'plant', text: 'Ургамал, мал, амьтан экспорт', resolutions: ['ЗГ №190', '№329 нэмэлт'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    proposedAdditions: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', targetResolution: 'ЗГ №173-д нэмэх', proposalNote: 'Хорио цээрийн лаборатори болон Шинжээч ГУБ байхгүй. Уул уурхайн экспортын гол боомтын хувьд лаборатори, агуулах байгуулах зайлшгүй хэрэгцээ бий.' },
      { goodId: 'animal', text: 'Мал, амьтан импорт', targetResolution: 'ЗГ №173-д нэмэх' },
      { goodId: 'meat', text: 'Түүхий мах импорт', targetResolution: 'ЗГ №173-д нэмэх' },
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', targetResolution: 'ЗГ №73-д нэмэх' },
      { goodId: 'chemical', text: 'Химийн хорт бодис', targetResolution: 'ЗГ №296-д нэмэх' },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', targetResolution: 'ЗГ №149-д нэмэх' },
    ],
  },
  { id: 'hanh', name: 'Ханх', region: 'Хөвсгөл', direction: 'Хойд', lat: 51.5, lng: 100.6, ubDistance: 1100, aimagDistance: 303, aimagLat: 49.63, aimagLng: 100.16, neighborPortName: "Монды (ОХУ)", operationalStatus: "Түр ажиллагаатай", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 100, 
    legalImports: [
      { goodId: 'animal', text: 'Мал, амьтан, үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'plant', text: 'Ургамлын үр, суулгац', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'pesticide', text: 'Ургамал хамгааллын бодис, бордоо', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 223-229к, ДТ: 226к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
  },
  { id: 'ereentsav', name: 'Эрээнцав', region: 'Дорнод', direction: 'Зүүн (Орос)', lat: 49.6, lng: 115.1, ubDistance: 943, aimagDistance: 245, aimagLat: 48.07, aimagLng: 114.53, neighborPortName: "Соловьевск (ОХУ)", operationalStatus: "Олон улсын", trafficStatus: "Хэвийн", transportTypes: ["Төмөр зам"], capacity: 400, 
    legalImports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173'] },
      { goodId: 'animal', text: 'Мал, амьтан, үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Шар айраг', resolutions: ['ЗГ №146/2023'], conditions: 'зөвхөн шар айраг' },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 750к, ДТ: 850к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    proposedAdditions: [
      { goodId: 'embryo', text: 'Мал амьтны үр, хөврөл үр, эмгэгт материал', targetResolution: 'ЗГ №173-д нэмэх', proposalNote: 'Хорио цээрийн ГУБ анхан шатны хяналт хийх боломжтой. Гүнзгийрүүлсэн лабораторийн шинжилгээг аймгийн төвд шинжлүүлдэг.' },
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', targetResolution: 'ЗГ №73-д нэмэх' },
    ],
  },
  { id: 'havirga', name: 'Хавирга', region: 'Дорнод', direction: 'Зүүн (Хятад)', lat: 47.5, lng: 115.1, ubDistance: 795, aimagDistance: 135, aimagLat: 48.07, aimagLng: 114.53, neighborPortName: "Ар хашаат (БНХАУ)", operationalStatus: "Хоёр талын", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 400, 
    development: {
      projectName: 'BEST худалдааг дэмжих төсөл (АХБ)',
      progress: 10,
      budget: '$13.22 сая ам.доллар (Нийт төслийн)',
      description: 'Ажлын зураг төслийн нэмэлт өөрчлөлт, техникийн тодорхойлолт боловсруулж дууссан. Хогийн цэг болон газар олголт шийдэгдсэн.',
    },
    legalImports: [
      { goodId: 'animal', text: 'Мал, амьтан, үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'pesticide', text: 'Ургамал хамгааллын бодис, бордоо', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'plant', text: 'Ургамал, мал, амьтан экспорт', resolutions: ['ЗГ №190', '№461 нэмэлт'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    proposedAdditions: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', targetResolution: 'ЗГ №173-д нэмэх', proposalNote: 'Хорио цээрийн лаборатори байхгүй. АХБ-ны төслөөр 2026 оноос хүнсний болон хорио цээрийн лаборатори баригдаж 2028 онд ашиглалтанд орно. Шинжээч-ГУБ бэлтгэх шаардлагатай.' },
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', targetResolution: 'ЗГ №73-д нэмэх' },
      { goodId: 'chemical', text: 'Химийн хорт бодис', targetResolution: 'ЗГ №296-д нэмэх' },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', targetResolution: 'ЗГ №149-д нэмэх' },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа импорт', targetResolution: 'ЗГ №146/2023-д нэмэх' },
    ],
  },
  { id: 'yarant', name: 'Ярант (Даян)', region: 'Ховд', direction: 'Баруун', lat: 46.7, lng: 90.9, ubDistance: 1890, aimagDistance: 212, neighborPortName: "Такашикэн (БНХАУ)", operationalStatus: "Түр ажиллагаатай", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 200, legalImports: [
    { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
  ], legalExports: [] },
  { id: 'baytag', name: 'Байтаг', region: 'Ховд', direction: 'Баруун', lat: 45.1, lng: 91.0, ubDistance: 1600, aimagDistance: 550, neighborPortName: "Улиастай (БНХАУ)", operationalStatus: "Түр ажиллагаатай", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 150, legalImports: [], legalExports: [] },
  { id: 'chinggis', name: 'Чингис хаан ОУНБ', region: 'Улаанбаатар', direction: 'Агаар', lat: 47.8431, lng: 106.7644, ubDistance: 0, aimagDistance: 0, operationalStatus: "Олон улсын", trafficStatus: "Хэвийн", transportTypes: ["Агаар"], capacity: 5000, 
    hasLaboratory: true,
    labCapabilities: ['Химийн бодис', 'Хүнс, ургамал, хорио цээр', 'Мансууруулах бодис'],
    legalImports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173'] },
      { goodId: 'animal', text: 'Мал, амьтан, үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'gmo', text: 'Хувиргасан амьд организм', resolutions: ['ЗГ №158'] },
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', resolutions: ['ЗГ №73'] },
      { goodId: 'chemical', text: 'Химийн хорт бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Бүх төрлийн согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    legalExports: [
      { goodId: 'embryo', text: 'Мал амьтны үр, хөврөл үр, эмгэгт материал', resolutions: ['ЗГ №173'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
  },
  { id: 'tsagaannuur', name: 'Цагааннуур', region: 'Баян-Өлгий', direction: 'Баруун (Орос)', lat: 49.5, lng: 89.4, ubDistance: 1900, aimagDistance: 100, aimagLat: 48.98, aimagLng: 89.97, neighborPortName: "Ташанта (ОХУ)", operationalStatus: "Олон улсын", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 600, 
    hasLaboratory: true,
    labCapabilities: ['Газрын тос', 'Ноос ноолуур, малын гаралтай ширхэгт материал', 'Хүнс, ургамал, хорио цээр'],
    legalImports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173'] },
      { goodId: 'animal', text: 'Мал, амьтан, үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'pesticide', text: 'Ургамал хамгааллын бодис, бордоо', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'alcohol', text: 'Шар айраг', resolutions: ['ЗГ №146/2023'], conditions: 'зөвхөн шар айраг' },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    proposedAdditions: [
      { goodId: 'embryo', text: 'Мал амьтны үр, хөврөл үр, эмгэгт материал', targetResolution: 'ЗГ №173-д нэмэх', proposalNote: 'АХБ-ны төслөөр 2027 оноос бүтээн байгуулалт эхэлж, хорио цээрийн лаборатори, агуулах байгуулагдана. Шинжээч-ГУБ орон тоог нэмэх шаардлагатай.' },
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', targetResolution: 'ЗГ №73-д нэмэх' },
      { goodId: 'chemical', text: 'Химийн хорт бодис', targetResolution: 'ЗГ №296-д нэмэх' },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', targetResolution: 'ЗГ №149-д нэмэх' },
    ],
  },
  { id: 'hangi', name: 'Ханги', region: 'Дорноговь', direction: 'Урд (Хятад)', lat: 42.9, lng: 110.1, ubDistance: 770, aimagDistance: 320, aimagLat: 44.8876, aimagLng: 110.1345, neighborPortName: "Мандал (БНХАУ)", operationalStatus: "Хоёр талын", trafficStatus: "Ачаалалтай", transportTypes: ["Автозам"], capacity: 900, 
    legalImports: [
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', resolutions: ['ЗГ №73', '№342 нэмэлт'] },
    ],
    legalExports: [
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    proposedAdditions: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', targetResolution: 'ЗГ №173-д нэмэх', proposalNote: 'Лаборатори байгуулах шаардлагатай. Хорио цээрийн лаборатори болон Шинжээч ГУБ байхгүй. Дээж аймгийн төвд шинжлүүлэхэд 3-5 хоног зарцуулагддаг.' },
      { goodId: 'animal', text: 'Мал, амьтан импорт', targetResolution: 'ЗГ №173-д нэмэх' },
      { goodId: 'embryo', text: 'Мал амьтны үр, хөвөрл үр', targetResolution: 'ЗГ №173-д нэмэх' },
      { goodId: 'meat', text: 'Түүхий мах импорт', targetResolution: 'ЗГ №173-д нэмэх' },
      { goodId: 'oil', text: 'Газрын тос импорт', targetResolution: 'ОАТ' },
    ],
  },
  { id: 'ulhan', name: 'Ульхан', region: 'Дорнод', direction: 'Зүүн', lat: 49.2, lng: 112.5, ubDistance: 740, aimagDistance: 270, aimagLat: 48.07, aimagLng: 114.53, neighborPortName: "Верхний Ульхун (ОХУ)", operationalStatus: "Хоёр талын", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 200, 
    legalImports: [
      { goodId: 'animal', text: 'Мал, амьтан, үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 223-229к, ДТ: 226к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    proposedAdditions: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', targetResolution: 'ЗГ №173-д нэмэх', proposalNote: 'Хорио цээрийн лаборатори болон Шинжээч ГУБ байхгүй. Дээж аймгийн төвд шинжлүүлэхэд 3-5 хоног зарцуулагддаг.' },
      { goodId: 'embryo', text: 'Мал амьтны үр, хөвөрл үр', targetResolution: 'ЗГ №173-д нэмэх' },
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', targetResolution: 'ЗГ №73-д нэмэх' },
    ],
  },
  { id: 'bayanhoshuu', name: 'Баянхошуу', region: 'Дорнод', direction: 'Зүүн (Хятад)', lat: 47.2, lng: 118.8, ubDistance: 1000, aimagDistance: 340, aimagLat: 48.07, aimagLng: 114.53, neighborPortName: "Өвдөг (БНХАУ)", operationalStatus: "Хоёр талын", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 300, 
    hasLaboratory: true,
    labCapabilities: ['Химийн бодис', 'Газрын тос'],
    legalImports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173', '№194 нэмэлт'] },
      { goodId: 'animal', text: 'Мал, амьтан, үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'chemical', text: 'Химийн хорт бодис', resolutions: ['ЗГ №296', '№66 нэмэлт'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №149', '№66 нэмэлт'] },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'plant', text: 'Ургамал, мал, амьтан экспорт', resolutions: ['ЗГ №190'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №149'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    proposedAdditions: [
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', targetResolution: 'ЗГ №73-д нэмэх', proposalNote: 'Хорио цээрийн ГУБ анхан шатны хяналт хийх боломжтой.' },
      { goodId: 'meat', text: 'Түүхий мах импорт', targetResolution: 'ЗГ №173-д нэмэх' },
    ],
  },
  { id: 'tes', name: 'Тэс', region: 'Увс', direction: 'Хойд', lat: 50.5, lng: 93.5, ubDistance: 1660, aimagDistance: 220, aimagLat: 49.98, aimagLng: 92.07, neighborPortName: "Шарсүр (ОХУ)", operationalStatus: "Хоёр талын", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 150, 
    legalImports: [
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
  },
  { id: 'artssuuri', name: 'Арцсуурь', region: 'Завхан', direction: 'Хойд', lat: 50.3, lng: 95.8, ubDistance: 1185, aimagDistance: 385, aimagLat: 47.74, aimagLng: 96.85, neighborPortName: "Цагаан-Толгой (ОХУ)", operationalStatus: "Хоёр талын", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 200, 
    legalImports: [
      { goodId: 'animal', text: 'Мал, амьтан, үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'plant', text: 'Ургамлын үр, суулгац', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'pesticide', text: 'Ургамал хамгааллын бодис, бордоо', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
  },
  { id: 'burgastay', name: 'Бургастай', region: 'Говь-Алтай', direction: 'Урд', lat: 44.8, lng: 93.9, ubDistance: 1320, aimagDistance: 320, aimagLat: 46.37, aimagLng: 96.26, neighborPortName: "Лаомяомяо (БНХАУ)", operationalStatus: "Хоёр талын", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 250, 
    legalImports: [
      { goodId: 'plant', text: 'Ургамлын үр, суулгац', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'pesticide', text: 'Ургамал хамгааллын бодис, бордоо', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    proposedAdditions: [
      { goodId: 'animal', text: 'Мал, амьтан импорт', targetResolution: 'ЗГ №173-д нэмэх', proposalNote: 'Хорио цээрийн лаборатори болон Шинжээч ГУБ байхгүй.' },
    ],
  },
  { id: 'tsumber', name: 'Сүмбэр', region: 'Дорнод', direction: 'Зүүн', lat: 47.6, lng: 118.6, ubDistance: 1135, aimagDistance: 425, aimagLat: 48.07, aimagLng: 114.53, neighborPortName: "Рашаант (БНХАУ)", operationalStatus: "Олон улсын", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 100, legalImports: [], legalExports: [] },
  { id: 'tsagaandel', name: 'Цагаандэл-Уул', region: 'Өмнөговь', direction: 'Урд', lat: 41.583, lng: 105.0, ubDistance: 770, aimagDistance: 195, aimagLat: 43.57, aimagLng: 104.42, neighborPortName: "Өлзий (БНХАУ)", operationalStatus: "Түр ажиллагаатай", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 200, 
    development: {
      projectName: '"Хөгжлийн хөтөч" дэд бүтцийн төсөл',
      progress: 15.4,
      budget: 'БНХАУ-ын тусламж 114.6 сая юань, МУ: 91 тэрбум ₮',
      description: 'Боомтын эхний ээлжид 16 барилга байгууламж, гадна инженерийн шугам сүлжээний барилга угсралтын ажил хийгдэж байна.',
      imageUrl: 'https://i0.wp.com/montsame.mn/files/6328320496da2.jpeg'
    },
    legalImports: [], legalExports: [] },
];

export const REGULATIONS: Record<string, RegulationRef> = {
  '173': {
    number: 'ЗГ №173',
    fullName: 'Жагсаалт, журам батлах тухай',
    date: '2003.07.15',
    amendments: ['№22/2010', '№190/2014', '№194/2015', '№461/2015', '№63/2016', '№198/2016', '№329/2017'],
    legalUrl: 'https://legalinfo.mn/mn/detail/2690',
    legalBasis: 'Хорио цээрийн хяналтын тухай хууль 5.1.5, 5.1.6, 5.1.7',
  },
  '158': {
    number: 'ЗГ №158',
    fullName: 'Хувиргасан амьд организмыг нэвтрүүлэх хилийн боомтын тухай',
    date: '2010',
    legalUrl: 'https://legalinfo.mn/mn/detail?lawId=5461',
    legalBasis: 'Хувиргасан амьд организмын тухай хуулийн 8.1',
  },
  '73': {
    number: 'ЗГ №73',
    fullName: 'Эм, эмнэлгийн хэрэгслийг улсын хилээр нэвтрүүлэх хилийн боомтыг тогтоох тухай',
    date: '2011',
    amendments: ['№239/2021', '№342/2021'],
    legalUrl: 'https://legalinfo.mn/mn/detail?lawId=5693',
    legalBasis: 'Эм, эмнэлгийн хэрэгслийн тухай хуулийн 14.1',
  },
  '296': {
    number: 'ЗГ №296',
    fullName: 'Химийн хорт болон аюултай бодисыг улсын хилээр нэвтрүүлэх боомтын жагсаалт',
    date: '2006',
    amendments: ['№66/2007', '№203/2010'],
    legalUrl: 'https://legalinfo.mn/mn/detail?lawId=5250',
    legalBasis: 'Химийн хорт болон аюултай бодисын тухай хуулийн 15.3',
  },
  '146/2011': {
    number: 'ЗГ №146/2011',
    fullName: 'Ургамлын үр, үрслэг, суулгац, ургамал хамгааллын бодис, бордоог жилд нэг удаа нэвтрүүлэх хилийн боомтыг тогтоох тухай',
    date: '2011',
    legalUrl: 'https://legalinfo.mn/mn/detail?lawId=4584',
  },
  '149': {
    number: 'ЗГ №149',
    fullName: 'Тэсэрч дэлбэрэх бодис, тэсэлгээний хэрэгслийг импортлох, экспортлоход улсын хилээр нэвтрүүлэх, дамжин өнгөрүүлэх хилийн боомтын жагсаалт',
    date: '2006.06.28',
    amendments: ['№66/2007', '№80/2010'],
    legalUrl: 'https://legalinfo.mn/mn/detail?lawId=2593',
  },
  '146/2023': {
    number: 'ЗГ №146/2023',
    fullName: 'Согтууруулах ундааг улсын хилээр нэвтрүүлэх боомтыг тогтоох тухай',
    date: '2023.04.19',
    legalUrl: 'https://legalinfo.mn/mn/detail?lawId=16759249742581',
    legalBasis: 'Согтууруулах ундааны эргэлтэд хяналт тавим тухай хуулийн 14.13',
  },
  '190': {
    number: 'ЗГ №190',
    fullName: 'Ургамлын үр, үрслэг, суулгац, мал, амьтан болон үржлийн мал экспортлох боомтуудын жагсаалт',
    date: '2014.06.14',
    amendments: ['№461/2015', '№329/2017'],
  },
};
