import { Good, BorderCrossing, PortGoodsMatrix, RegulationRef } from "./types";

export const GOODS: Good[] = [
  { id: 'plant', icon: '🌱', name: 'Ургамлын үр, үрслэг, суулгац', sources: { import: 'ЗГ №173', export: 'ЗГ №190' }, detail: 'Ургамлын үр, үрслэг, суулгац нэвтрүүлэх.' },
  { id: 'animal', icon: '🐄', name: 'Мал, амьтан', sources: { import: 'ЗГ №173', export: 'ЗГ №173' }, detail: 'Мал, амьтан нэвтрүүлэх (цугт нь).' },
  { id: 'breeding_animal', icon: '🐎', name: 'Үржлийн мал', sources: { import: 'ЗГ №173', export: 'ЗГ №173' }, detail: 'Үржлийн мал импортлох, экспортлох.' },
  { id: 'embryo', icon: '🧬', name: 'Мал амьтны үр, хөврөл үр', sources: { import: 'ЗГ №173', export: 'ЗГ №173' }, detail: 'Мал амьтны үр, хөврөл үр, бичил биетний өсгөвөр, эмгэгт материал.' },
  { id: 'meat', icon: '🥩', name: 'Түүхий мах, дайвар бүтээгдэхүүн', sources: { import: 'ЗГ №173', export: 'ЗГ №173' }, detail: 'Түүхий мах болон дайвар бүтээгдэхүүн.' },
  { id: 'medicine', icon: '💊', name: 'Эм, эмнэлгийн хэрэгсэл', sources: { import: 'ЗГ №73', export: 'ЗГ №73' }, detail: 'Эм, эмнэлгийн хэрэгсэл.' },
  { id: 'chemical', icon: '☣️', name: 'Химийн хорт болон аюултай бодис', sources: { import: 'ЗГ №296', export: 'ЗГ №296' }, detail: 'Химийн хорт ба аюултай бодис.' },
  { id: 'explosive', icon: '💥', name: 'Тэсэрч дэлбэрэх бодис', sources: { import: 'ЗГ №215', export: 'ЗГ №215' }, detail: 'Тэсэрч дэлбэрэх бодис ба тэсэлгээний хэрэгсэл.' },
  { id: 'alcohol', icon: '🍺', name: 'Согтууруулах ундаа', sources: { import: 'ЗГ №146/2023', export: 'ЗГ №146/2023' }, detail: 'Бүх төрлийн согтууруулах ундаа.' },
  { id: 'pesticide', icon: '🌾', name: 'Ургамал хамгааллын бодис, бордоо', sources: { import: 'ЗГ №146/2011', export: 'ЗГ №146/2011' }, detail: 'Ургамал хамгааллын бодис, бордоо.' },
  { id: 'gmo', icon: '🧪', name: 'Хувиргасан амьд организм', sources: { import: 'ЗГ №158', export: 'ЗГ №158' }, detail: 'Хувиргасан амьд организм (ГМО).' },
  { id: 'oil', icon: '⛽', name: 'Газрын тосны бүтээгдэхүүн', sources: { import: 'Онцгой албан татвар', export: 'Онцгой албан татвар' }, detail: 'Автобензин, дизелийн түлш.' },
];

export const borderCrossings: BorderCrossing[] = [
  { 
    id: 'zamiin-uud', 
    name: 'Замын-Үүд', 
    region: 'Дорноговь', 
    direction: 'Зүүн (Хятад)', 
    lat: 111.9066, 
    lng: 43.7180, 
    ubDistance: 650, 
    aimagDistance: 210, 
    aimagLat: 110.1345,
    aimagLng: 44.8876, // Sainshand (Dornogovi)
    neighborPortName: "Эрээн (БНХАУ)",
    operationalStatus: "Олон улсын", 
    trafficStatus: "Ачаалалтай",
    transportTypes: ["Автозам", "Төмөр зам"],
    capacity: 1500,
    development: {
      projectName: '"Хөгжлийн хөтөч" дэд бүтцийн төсөл',
      progress: 100,
      budget: 'МУ: 25.5 тэрбум ₮, БНХАУ: 106.9 тэрбум ₮',
      contractor: 'Жун Мэй Инженеринг Групп ХХК',
      description: 'Хилийн боомтын дэд бүтэц, барилга байгууламжийн шинэчлэл бүрэн дууссан. Зорчигч болон ачаа тээврийн цогцолбор ашиглалтад орсон.',
      imageUrl: 'https://i0.wp.com/cdn.mminfo.mn/sh/mminfo/2024/01/21/11/04/30/1e0ffae78d594b29f0464670b8a24ca3.jpg'
    },
    areaSize: 25000,
    staffGUAB: 45,
    staffGUB: 120,
    warehousesCount: 8,
    controlZonesCount: 4,
    imageUrl: "https://i0.wp.com/upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Zamiin_Uud_border_crossing.jpg/640px-Zamiin_Uud_border_crossing.jpg",
    description: "Монгол Улсын хамгийн том, стратегийн чухал ач холбогдолтой хилийн боомт. Ачаа болон зорчигч тээврийн гол зангилаа.",
    hasLaboratory: true,
    labCapacity: "Гаалийн төв лабораторын салбар лаборатори",
    labCapabilities: [
      "Хүнсний эрүүл ахуй, хорио цээр",
      "Химийн хорт болон аюултай бодис",
      "Эрдэс баялаг, нүүрс",
      "Мансууруулах болон сэтгэцэд нөлөөт бодис",
      "Ноос, ноолуур, малын гаралтай ширхэгт материал"
    ],
    infrastructure: {
      totalArea: "18.6 га",
      details: ["Шалган нэвтрүүлэх цогцолбор шинэчлэгдсэн", "Ухаалаг гарц системтэй", "Хүчин чадал 5 дахин нэмэгдсэн"]
    },
    legalImports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173'] },
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'] },
      { goodId: 'breeding_animal', text: 'Үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'embryo', text: 'Мал амьтны үр, хөврөл үр', resolutions: ['ЗГ №173'] },
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', resolutions: ['ЗГ №73'] },
      { goodId: 'chemical', text: 'Химийн хорт болон аюултай бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
      { goodId: 'alcohol', text: 'Бүх төрлийн согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 750к, ДТ: 850к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173', 'ЗГ №190'] },
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'] },
      { goodId: 'breeding_animal', text: 'Үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'embryo', text: 'Мал амьтны үр, хөврөл үр', resolutions: ['ЗГ №173'] },
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', resolutions: ['ЗГ №73'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'chemical', text: 'Химийн хорт болон аюултай бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
  },
  { 
    id: 'altanbulag', 
    name: 'Алтанбулаг', 
    region: 'Сэлэнгэ', 
    direction: 'Хойд (Орос)', 
    lat: 106.4950, 
    lng: 50.3168, 
    ubDistance: 350, 
    aimagDistance: 23, 
    aimagLat: 106.2000,
    aimagLng: 50.2333, // Sukhbaatar (Selenge)
    neighborPortName: "Хиагт (ОХУ)",
    operationalStatus: "Олон улсын", 
    trafficStatus: "Хэвийн",
    transportTypes: ["Автозам"],
    capacity: 800,
    development: {
      projectName: 'RIBS бүс нутгийн төсөл (АХБ)',
      progress: 100,
      budget: '$12.1 сая ам.доллар',
      contractor: '"Эйч Кэ Би Интернэйшнл Холдинг" ХХК',
      description: 'Алтанбулаг боомтын барилга байгууламжийг сайжруулах, өргөтгөх, шинэчлэх ажил 100% дууссан.',
      imageUrl: 'https://i0.wp.com/montsame.mn/files/612de34d284a8.jpeg'
    },
    hasLaboratory: true,
    labCapacity: "Гаалийн төв лабораторын салбар лаборатори",
    labCapabilities: ["Хүнсний эрүүл ахуй, хорио цээр", "Химийн хорт болон аюултай бодис", "Мансууруулах болон сэтгэцэд нөлөөт бодис", "Архи, согтууруулах ундаа"],
    infrastructure: {
      totalArea: "7.13 га",
      passengerZone: "3.37 га",
      cargoZone: "3.43 га",
      details: ["Дэд бүтцийн хэсэг: 0.33 га", "Олон улсын жишигт нийцсэн шинэ цогцолбор", "Зорчигч тээвэрлэх хүчин чадал: 2.22 га талбайтай"]
    },
    legalImports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173'] },
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'] },
      { goodId: 'breeding_animal', text: 'Үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'embryo', text: 'Мал амьтны үр, хөврөл үр', resolutions: ['ЗГ №173'] },
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', resolutions: ['ЗГ №73'] },
      { goodId: 'chemical', text: 'Химийн хорт болон аюултай бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
      { goodId: 'alcohol', text: 'Бүх төрлийн согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 750к, ДТ: 850к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173', 'ЗГ №190'] },
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'] },
      { goodId: 'breeding_animal', text: 'Үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'embryo', text: 'Мал амьтны үр, хөврөл үр', resolutions: ['ЗГ №173'] },
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', resolutions: ['ЗГ №73'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'chemical', text: 'Химийн хорт болон аюултай бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
  },
  { 
    id: 'bichigt', 
    name: 'Бичигт', 
    region: 'Сүхбаатар', 
    direction: 'Зүүн (Хятад)', 
    lat: 116.2730, 
    lng: 45.7602, 
    ubDistance: 850, 
    aimagDistance: 295, 
    aimagLat: 113.2847,
    aimagLng: 46.6806, // Baruun-Urt (Sukhbaatar)
    neighborPortName: "Зүүн хатавч (БНХАУ)",
    operationalStatus: "Олон улсын", 
    trafficStatus: "Хэвийн",
    transportTypes: ["Автозам"],
    capacity: 500,
    development: {
      projectName: 'RIBS бүс нутгийн төсөл (АХБ)',
      progress: 35,
      budget: '$8.4 сая ам.доллар',
      description: 'Боомтын барилга байгууламж, дэд бүтцийн ажил үргэлжилж байна.',
      imageUrl: 'https://i0.wp.com/montsame.mn/files/64757c2c01ca7.jpeg'
    },
    infrastructure: {
      totalArea: "14 га",
      passengerZone: "4.97 га",
      cargoZone: "5.12 га",
      details: ["Хил хамгаалалтын бүс: 1.5 га", "Инженер хангамжийн бүс: 0.95 га", "Ачаа тээврийн цогцолбор: 5.12 га"]
    },
    legalImports: [
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'] },
      { goodId: 'breeding_animal', text: 'Үржлийн мал (зөвхөн адуу)', resolutions: ['ЗГ №173'], conditions: 'зөвхөн үржлийн адуу импортоор оруулах' },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'chemical', text: 'Химийн хорт болон аюултай бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215', '№66 нэмэлт'] },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'] },
      { goodId: 'plant', text: 'Ургамал экспорт', resolutions: ['ЗГ №190'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'chemical', text: 'Химийн хорт болон аюултай бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    proposedAdditions: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', targetResolution: 'ЗГ №173-д нэмэх', proposalNote: 'Лаборатори байгуулах шаардлагатай. Хорио цээрийн лаборатори болон Шинжээч ГУБ байхгүй. АХБ-ны төслийн хүрээнд 2026 оноос шинэчлэл хийгдэж 2028 онд ашиглалтанд орно.' },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа импорт', targetResolution: 'ЗГ №146/2023-д нэмэх' },
    ],
  },
  { 
    id: 'borshoo', 
    name: 'Боршоо', 
    region: 'Увс', 
    direction: 'Хойд (Орос)', 
    lat: 92.4285, 
    lng: 50.6728, 
    ubDistance: 1600, 
    aimagDistance: 124, 
    aimagLat: 92.0667,
    aimagLng: 49.9800, // Ulaangom (Uvs)
    neighborPortName: "Хандагайты (ОХУ)",
    operationalStatus: "Олон улсын", 
    trafficStatus: "Хэвийн",
    transportTypes: ["Автозам"],
    capacity: 500,
    development: {
      projectName: 'RIBS бүс нутгийн төсөл (АХБ)',
      progress: 100,
      budget: '$7.6 сая ам.доллар',
      description: 'Боршоо хилийн боомтын барилга байгууламж, тоног төхөөрөмжийг сайжруулах, өргөтгөх ажил дууссан.',
      imageUrl: 'https://i0.wp.com/montsame.mn/files/653243fcc889f.jpeg'
    },
    hasLaboratory: true,
    labCapabilities: ['Хүнс, ургамал, хорио цээр'],
    infrastructure: {
      totalArea: "10 га",
      passengerZone: "3232.0 м2 (Танхим)",
      details: ["Ерөнхий төлөвлөгөөний дагуу шинэчлэгдсэн", "Ачаа тээвэрлэх тусгай бүстэй"]
    },
    legalImports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173'] },
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'] },
      { goodId: 'breeding_animal', text: 'Үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'pesticide', text: 'Ургамал хамгааллын бодис, бордоо', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173', 'ЗГ №190'] },
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'pesticide', text: 'Ургамал хамгааллын бодис, бордоо', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    proposedAdditions: [
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', targetResolution: 'ЗГ №73-д нэмэх' },
    ],
  },
  { id: 'hanh', name: 'Ханх', region: 'Хөвсгөл', direction: 'Хойд (Орос)', lat: 100.65, lng: 51.52, ubDistance: 1100, aimagDistance: 303, aimagLat: 100.16, aimagLng: 49.63, neighborPortName: "Монды (ОХУ)", operationalStatus: "Түр ажиллагаатай", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 100, 
    legalImports: [
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'] },
      { goodId: 'breeding_animal', text: 'Үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'plant', text: 'Ургамлын үр, суулгац', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'pesticide', text: 'Ургамал хамгааллын бодис, бордоо', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'oil', text: 'Газрных тос (Бензин: 223-229к, ДТ: 226к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'pesticide', text: 'Ургамал хамгааллын бодис, бордоо', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
  },
  { id: 'yarant', name: 'Ярант (Даян)', region: 'Ховд', direction: 'Баруун', lat: 91.5647, lng: 46.1264, ubDistance: 1890, aimagDistance: 212, neighborPortName: "Такашикэн (БНХАУ)", operationalStatus: "Түр ажиллагаатай", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 200, legalImports: [
    { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
  ], legalExports: [] },
  { id: 'gashuunsuhayt', name: 'Гашуунсухайт', region: 'Өмнөговь', direction: 'Урд (Хятад)', lat: 107.1352, lng: 43.0848, ubDistance: 800, aimagDistance: 342, aimagLat: 104.42, aimagLng: 43.57, neighborPortName: "Ганцмод (БНХАУ)", operationalStatus: "Олон улсын", trafficStatus: "Ачаалалтай", transportTypes: ["Автозам", "AGV"], capacity: 1200, 
    hasLaboratory: true,
    labCapabilities: ['Нүүрс', 'Зэс'],
    legalImports: [
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
      { goodId: 'chemical', text: 'Химийн хорт болон аюултай бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
      { goodId: 'chemical', text: 'Химийн хорт болон аюултай бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    proposedAdditions: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', targetResolution: 'ЗГ №173-д нэмэх', proposalNote: 'Хорио цээрийн лаборатори байхгүй, дээж аймгийн төвд шинжлэгддэг.' },
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', targetResolution: 'ЗГ №73-д нэмэх' },
    ],
  },
  { id: 'bulgan', name: 'Булган', region: 'Ховд', direction: 'Баруун', lat: 91.5647, lng: 46.1264, ubDistance: 1650, aimagDistance: 380, neighborPortName: "Такашикэн (БНХАУ)", operationalStatus: "Олон улсын", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 300, 
    legalImports: [
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
      { goodId: 'alcohol', text: 'Шар айраг', resolutions: ['ЗГ №146/2023'], conditions: 'зөвхөн шар айраг' },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173', 'ЗГ №190'] },
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
    ],
  },
  { id: 'ulhan', name: 'Ульхан', region: 'Дорнод', direction: 'Зүүн', lat: 113.1700, lng: 49.3500, ubDistance: 740, aimagDistance: 270, aimagLat: 114.53, aimagLng: 48.07, neighborPortName: "Верхний Ульхун (ОХУ)", operationalStatus: "Хоёр талын", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 200, 
    legalImports: [
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'] },
      { goodId: 'breeding_animal', text: 'Үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 223-229к, ДТ: 226к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    proposedAdditions: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', targetResolution: 'ЗГ №173-д нэмэх', proposalNote: 'Хорио цээрийн лаборатори болон Шинжээч ГУБ байхгүй. Дээж аймгийн төвд шинжлүүлэхэд 3-5 хоног зарцуулагддаг.' },
      { goodId: 'embryo', text: 'Мал амьтны үр, хөврөл үр', targetResolution: 'ЗГ №173-д нэмэх' },
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', targetResolution: 'ЗГ №73-д нэмэх' },
    ],
  },
  { id: 'bayanhoshuu', name: 'Баянхошуу', region: 'Дорнод', direction: 'Зүүн (Хятад)', lat: 119.3100, lng: 47.9400, ubDistance: 1000, aimagDistance: 340, aimagLat: 114.53, aimagLng: 48.07, neighborPortName: "Өвдөг (БНХАУ)", operationalStatus: "Хоёр талын", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 300, 
    hasLaboratory: true,
    labCapabilities: ['Химийн бодис', 'Газрын тос'],
    legalImports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173', '№194 нэмэлт'] },
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'] },
      { goodId: 'breeding_animal', text: 'Үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'chemical', text: 'Химийн хорт болон аюултай бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215', '№66 нэмэлт'] },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173', '№194 нэмэлт', 'ЗГ №190'] },
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'chemical', text: 'Химийн хорт болон аюултай бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    proposedAdditions: [
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', targetResolution: 'ЗГ №73-д нэмэх', proposalNote: 'Хорио цээрийн ГУБ анхан шатны хяналт хийх боломжтой.' },
      { goodId: 'meat', text: 'Түүхий мах импорт', targetResolution: 'ЗГ №173-д нэмэх' },
    ],
  },
  { id: 'tes', name: 'Тэс', region: 'Увс', direction: 'Хойд', lat: 93.6350, lng: 50.5480, ubDistance: 1660, aimagDistance: 220, aimagLat: 92.07, aimagLng: 49.98, neighborPortName: "Шарсүр (ОХУ)", operationalStatus: "Хоёр талын", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 150, 
    legalImports: [
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
  },
  { id: 'artssuuri', name: 'Арцсуурь', region: 'Завхан', direction: 'Хойд', lat: 94.6050, lng: 50.2740, ubDistance: 1185, aimagDistance: 385, aimagLat: 96.85, aimagLng: 47.74, neighborPortName: "Цагаан-Толгой (ОХУ)", operationalStatus: "Хоёр талын", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 200, 
    legalImports: [
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'] },
      { goodId: 'breeding_animal', text: 'Үржлийн мал', resolutions: ['ЗГ №173'] },
      { goodId: 'plant', text: 'Ургамлын үр, суулгац', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'pesticide', text: 'Ургамал хамгааллын бодис, бордоо', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'animal', text: 'Мал, амьтан', resolutions: ['ЗГ №173'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'pesticide', text: 'Ургамал хамгааллын бодис, бордоо', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
  },
  { id: 'tsumber', name: 'Сүмбэр', region: 'Дорнод', direction: 'Зүүн', lat: 118.6, lng: 47.6, ubDistance: 1135, aimagDistance: 425, aimagLat: 114.53, aimagLng: 48.07, neighborPortName: "Рашаант (БНХАУ)", operationalStatus: "Олон улсын", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 100, 
    legalImports: [], 
    legalExports: [],
    proposedAdditions: [
      { goodId: 'embryo', text: 'Мал амьтны үр, хөврөл үр', targetResolution: 'ЗГ №173-д нэмэх' },
      { goodId: 'meat', text: 'Түүхий мах импорт', targetResolution: 'ЗГ №173-д нэмэх' },
      { goodId: 'oil', text: 'Газрын тос импорт', targetResolution: 'ОАТ' },
    ],
  },
  { id: 'tsagaandel', name: 'Цагаандэл-Уул', region: 'Өмнөговь', direction: 'Урд', lat: 105.0, lng: 41.583, ubDistance: 770, aimagDistance: 195, aimagLat: 104.42, aimagLng: 43.57, neighborPortName: "Өлзий (БНХАУ)", operationalStatus: "Түр ажиллагаатай", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 200, 
    development: {
      projectName: '"Хөгжлийн хөтөч" дэд бүтцийн төсөл',
      progress: 15.4,
      budget: 'БНХАУ-ын тусламж 114.6 сая юань, МУ: 91 тэрбум ₮',
      description: 'Боомтын эхний ээлжид 16 барилга байгууламж, гадна инженерийн шугам сүлжээний барилга угсралтын ажил хийгдэж байна.',
      imageUrl: 'https://i0.wp.com/montsame.mn/files/6328320496da2.jpeg'
    },
    legalImports: [], 
    legalExports: [] 
  },
  { id: 'burgastay', name: 'Бургастай', region: 'Говь-Алтай', direction: 'Урд', lat: 93.9, lng: 44.8, ubDistance: 1320, aimagDistance: 320, aimagLat: 96.26, aimagLng: 46.37, neighborPortName: "Лаомяомяо (БНХАУ)", operationalStatus: "Хоёр талын", trafficStatus: "Хэвийн", transportTypes: ["Автозам"], capacity: 250, legalImports: [{ goodId: 'plant', text: 'Ургамлын үр, суулгац', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' }, { goodId: 'pesticide', text: 'Ургамал хамгааллын бодис, бордоо', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' }, { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] }], legalExports: [{ goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] }, { goodId: 'pesticide', text: 'Ургамал хамгааллын бодис, бордоо', resolutions: ['ЗГ №146/2011'], conditions: 'жилд 1 удаа' }, { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] }], proposedAdditions: [{ goodId: 'animal', text: 'Мал, амьтан импорт', targetResolution: 'ЗГ №173-д нэмэх', proposalNote: 'Хорио цээрийн лаборатори болон Шинжээч ГУБ байхгүй.' }] },
  { 
    id: 'sukhbaatar', 
    name: 'Сүхбаатар', 
    region: 'Сэлэнгэ', 
    direction: 'Хойд (Орос)', 
    lat: 106.2000, 
    lng: 50.2333, 
    ubDistance: 311, 
    aimagDistance: 0, 
    neighborPortName: "Наушки (ОХУ)", 
    operationalStatus: "Олон улсын", 
    trafficStatus: "Хэвийн", 
    transportTypes: ["Төмөр зам"], 
    capacity: 1000,
    legalImports: [
      { goodId: 'plant', text: 'Ургамлын үр, үрслэг, суулгац', resolutions: ['ЗГ №173'] },
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', resolutions: ['ЗГ №73'] },
      { goodId: 'chemical', text: 'Химийн хорт болон аюултай бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
    ],
    legalExports: [
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
      { goodId: 'chemical', text: 'Химийн хорт болон аюултай бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
    ]
  },
  { 
    id: 'chinggis-khaan', 
    name: 'Чингис хаан олон улсын нисэх буудал', 
    region: 'Улаанбаатар', 
    direction: 'Агаар', 
    lat: 106.76, 
    lng: 47.64, 
    ubDistance: 50, 
    aimagDistance: 0, 
    neighborPortName: "Олон улсын нисэх буудлууд", 
    operationalStatus: "Олон улсын", 
    trafficStatus: "Хэвийн", 
    transportTypes: ["Агаар"], 
    category: "Боомт",
    capacity: 2000,
    hasLaboratory: true,
    labCapabilities: ["Химийн бодис", "Мансууруулах бодис", "Гоо сайхан"],
    legalImports: [
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', resolutions: ['ЗГ №73'] },
      { goodId: 'chemical', text: 'Химийн хорт болон аюултай бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ],
    legalExports: [
      { goodId: 'medicine', text: 'Эм, эмнэлгийн хэрэгсэл', resolutions: ['ЗГ №73'] },
      { goodId: 'chemical', text: 'Химийн хорт болон аюултай бодис', resolutions: ['ЗГ №296'] },
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
      { goodId: 'alcohol', text: 'Согтууруулах ундаа', resolutions: ['ЗГ №146/2023'] },
    ]
  },
  { 
    id: 'shiveehuren', 
    name: 'Шивээхүрэн', 
    region: 'Өмнөговь', 
    direction: 'Урд (Хятад)', 
    lat: 101.4402, 
    lng: 43.0375, 
    ubDistance: 850, 
    aimagDistance: 320, 
    neighborPortName: "Цэхэ (БНХАУ)", 
    operationalStatus: "Олон улсын", 
    trafficStatus: "Хэвийн", 
    transportTypes: ["Автозам"], 
    capacity: 800,
    legalImports: [
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
    ]
  },
  { 
    id: 'hangi', 
    name: 'Ханги', 
    region: 'Дорноговь', 
    direction: 'Урд (Хятад)', 
    lat: 109.1558, 
    lng: 43.2030, 
    ubDistance: 460, 
    aimagDistance: 280, 
    neighborPortName: "Мандал (БНХАУ)", 
    operationalStatus: "Хоёр талын", 
    trafficStatus: "Хэвийн", 
    transportTypes: ["Автозам"], 
    capacity: 500,
    legalImports: [
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
    ]
  },
  { 
    id: 'ereentsav', 
    name: 'Эрээнцав', 
    region: 'Дорнод', 
    direction: 'Зүүн (Орос)', 
    lat: 115.4500, 
    lng: 49.5667, 
    ubDistance: 830, 
    aimagDistance: 270, 
    neighborPortName: "Соловьевск (ОХУ)", 
    operationalStatus: "Хоёр талын", 
    trafficStatus: "Хэвийн", 
    transportTypes: ["Автозам", "Төмөр зам"], 
    capacity: 200,
    legalImports: [
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
    ],
    legalExports: [
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
      { goodId: 'meat', text: 'Түүхий мах, дайвар бүтээгдэхүүн', resolutions: ['ЗГ №173'] },
    ]
  },
  { 
    id: 'tsagaannuur', 
    name: 'Цагааннуур', 
    region: 'Баян-Өлгий', 
    direction: 'Баруун (Орос)', 
    lat: 89.2818, 
    lng: 49.5255, 
    ubDistance: 1750, 
    aimagDistance: 85, 
    neighborPortName: "Ташанта (ОХУ)", 
    operationalStatus: "Олон улсын", 
    trafficStatus: "Хэвийн", 
    transportTypes: ["Автозам"], 
    capacity: 300,
    legalImports: [
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
      { goodId: 'oil', text: 'Газрын тос (Бензин: 215-217к, ДТ: 221к)', resolutions: ['ОАТ'] },
    ],
    legalExports: [
      { goodId: 'explosive', text: 'Тэсэрч дэлбэрэх бодис', resolutions: ['ЗГ №215'] },
    ]
  },
  // Гүний гааль
  {
    id: 'ub-deep-customs',
    name: 'Улаанбаатар дахь гүний гаалийн газар',
    region: 'Улаанбаатар',
    direction: 'Дотоод',
    category: 'Гүний гааль',
    lat: 106.85,
    lng: 47.91,
    ubDistance: 0,
    aimagDistance: 0,
    operationalStatus: 'Олон улсын',
    trafficStatus: 'Хэвийн',
    transportTypes: ['Автозам', 'Төмөр зам'],
    capacity: 2000,
    legalImports: [],
    legalExports: []
  },
  {
    id: 'darkhan-deep-customs',
    name: 'Дархан дахь гүний гааль',
    region: 'Дархан-Уул',
    direction: 'Дотоод',
    category: 'Гүний гааль',
    lat: 105.95,
    lng: 49.48,
    ubDistance: 230,
    aimagDistance: 0,
    operationalStatus: 'Олон улсын',
    trafficStatus: 'Хэвийн',
    transportTypes: ['Автозам', 'Төмөр зам'],
    capacity: 500,
    legalImports: [],
    legalExports: []
  },
  // Хяналтын бүс
  {
    id: 'control-zone-1',
    name: 'Нисэх - Хяналтын бүс',
    region: 'Улаанбаатар',
    direction: 'Агаар',
    category: 'Хяналтын бүс',
    lat: 106.76,
    lng: 47.64,
    ubDistance: 50,
    aimagDistance: 0,
    operationalStatus: 'Олон улсын',
    trafficStatus: 'Хэвийн',
    transportTypes: ['Агаар'],
    capacity: 1000,
    legalImports: [],
    legalExports: []
  },
  // Баталгаат бүс
  {
    id: 'bonded-zone-1',
    name: 'Эмээлт - Баталгаат бүс',
    region: 'Улаанбаатар',
    direction: 'Дотоод',
    category: 'Баталгаат бүс',
    lat: 106.62,
    lng: 47.88,
    ubDistance: 35,
    aimagDistance: 0,
    operationalStatus: 'Олон улсын',
    trafficStatus: 'Хэвийн',
    transportTypes: ['Автозам'],
    capacity: 1500,
    legalImports: [],
    legalExports: []
  },
  // Чөлөөт бүс
  {
    id: 'free-zone-zamiin-uud',
    name: 'Замын-Үүд Чөлөөт бүс',
    region: 'Дорноговь',
    direction: 'Урд',
    category: 'Чөлөөт бүс',
    lat: 111.92,
    lng: 43.68,
    ubDistance: 650,
    aimagDistance: 210,
    operationalStatus: 'Олон улсын',
    trafficStatus: 'Хэвийн',
    transportTypes: ['Автозам'],
    capacity: 2000,
    legalImports: [],
    legalExports: []
  },
  {
    id: 'free-zone-altanbulag',
    name: 'Алтанбулаг Чөлөөт бүс',
    region: 'Сэлэнгэ',
    direction: 'Хойд',
    category: 'Чөлөөт бүс',
    lat: 106.48,
    lng: 50.32,
    ubDistance: 350,
    aimagDistance: 23,
    operationalStatus: 'Олон улсын',
    trafficStatus: 'Хэвийн',
    transportTypes: ['Автозам'],
    capacity: 1000,
    legalImports: [],
    legalExports: []
  },
];

export const REGULATIONS: Record<string, RegulationRef> = {
  '173': {
    number: 'ЗГ №173',
    fullName: 'Жагсаалт, журам батлах тухай',
    date: '2003.07.15',
    amendments: ['№22/2010', '№190/2014', '№194/2015', '№461/2015', '№63/2016', '№198/2016', '№329/2017'],
    legalUrl: 'https://legalinfo.mn/mn/detail/2690',
    legalBasis: 'Хорио цээрийн хяналтын тухай хууль 5.1.5, 5.1.6, 5.1.7',
  },
  '158': {
    number: 'ЗГ №158',
    fullName: 'Хувиргасан амьд организмыг нэвтрүүлэх хилийн боомтын тухай',
    date: '2010',
    legalUrl: 'https://legalinfo.mn/mn/detail?lawId=5461',
    legalBasis: 'Хувиргасан амьд организмын тухай хуулийн 8.1',
  },
  '73': {
    number: 'ЗГ №73',
    fullName: 'Эм, эмнэлгийн хэрэгслийг улсын хилээр нэвтрүүлэх хилийн боомтыг тогтоох тухай',
    date: '2011',
    amendments: ['№239/2021', '№342/2021'],
    legalUrl: 'https://legalinfo.mn/mn/detail?lawId=5693',
    legalBasis: 'Эм, эмнэлгийн хэрэгслийн тухай хуулийн 14.1',
  },
  '296': {
    number: 'ЗГ №296',
    fullName: 'Химийн хорт болон аюултай бодисыг улсын хилээр нэвтрүүлэх боомтын жагсаалт',
    date: '2006',
    amendments: ['№66/2007', '№203/2010'],
    legalUrl: 'https://legalinfo.mn/mn/detail?lawId=5250',
    legalBasis: 'Химийн хорт болон аюултай бодисын тухай хуулийн 15.3',
  },
  '146/2011': {
    number: 'ЗГ №146/2011',
    fullName: 'Ургамлын үр, үрслэг, суулгац, ургамал хамгааллын бодис, бордоог жилд нэг удаа нэвтрүүлэх хилийн боомтыг тогтоох тухай',
    date: '2011',
    legalUrl: 'https://legalinfo.mn/mn/detail?lawId=4584',
  },
  '215': {
    number: 'ЗГ №215',
    fullName: 'Тэсэрч дэлбэрэх бодис, тэсэлгээний хэрэгслийг импортлох, экспортлох улсын хилээр нэвтрүүлэх хилийн боомтын жагсаалт батлах тухай',
    date: '2022.05.31',
    legalUrl: 'https://legalinfo.mn/mn/detail?lawId=16530539968251',
    legalBasis: 'Тэсэрч дэлбэрэх бодис, тэсэлгээний хэрэгслийн эргэлтэд хяналт тавих тухай хуулийн 10.3',
  },
  '146/2023': {
    number: 'ЗГ №146/2023',
    fullName: 'Согтууруулах ундааг улсын хилээр нэвтрүүлэх боомтыг тогтоох тухай',
    date: '2023.04.19',
    legalUrl: 'https://legalinfo.mn/mn/detail?lawId=16759249742581',
    legalBasis: 'Согтууруулах ундааны эргэлтэд хяналт тавим тухай хуулийн 14.13',
  },
  '190': {
    number: 'ЗГ №190',
    fullName: 'Ургамлын үр, үрслэг, суулгац, мал, амьтан болон үржлийн мал экспортлох боомтуудын жагсаалт',
    date: '2014.06.14',
    amendments: ['№461/2015', '№329/2017'],
  },
};
